### ISSUE TITLE
Fix Eslint to use React.Fragment

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#10]
**Describe Bug**
- current linting prints error when using `React.Fragment` or `Fragment`: 
```bash
Prefer fragment shorthand over React.Fragment 
```
- however, shorthand's (`<>` ) highlighting looks weird in GitHub,

![image](https://user-images.githubusercontent.com/29671309/70600874-2b62e500-1c34-11ea-9cf0-bdd74dff23f0.png)

**Expected Behavior**
- linting should enable using `React.Fragment` or `Fragment`
- print error when using fragment shorthand to prefer not using shorthand syntax

**Comment by helfi92** [comment]
Oh, we can use `@mozilla-frontend-infra/react-lint` which extends the airbnb presets. It has some additions one of which will hopefully fix the `<>` issue.

We can just remove the airbnb preset and replace it with `react-lint`.
