### ISSUE TITLE
Use a monospace font on the left side

### ISSUE THREAD

**Issue by djmitche** [taskcluster/material-ui-json-schema-viewer#115]
The left panel is supposed to be the JSON content, so let's show it in a monospace "code" font.

**Comment by jpetto** [comment]
_reserving for pocket curation tools outreachy applicants_

**Comment by Joaquin-M2** [comment]
I would like to be assigned to fix this issue too, if that's fine with everyone. I will also (try to) apply the Git suggestion @djmitche did on my PR #121 .

**Comment by djmitche** [comment]
All yours!

**Comment by Joaquin-M2** [comment]
@djmitche , when changing the font family to monospace, the affected text is shrinked a little bit because of the new font family applied. It is not a huge change on the size of the font, but in my opinion the change is big enough to require increasing a bit the font size.

![image](https://user-images.githubusercontent.com/61671655/99423314-b6e2fc80-2900-11eb-9a69-b32c6d5c0445.png)

Should I apply the change on the font size on the same PR for this issue #115, or I should better create a new issue describing the need of increasing a bit the font size?

**Comment by djmitche** [comment]
@helfi92 what do you think?

**Comment by Joaquin-M2** [comment]
@djmitche, when re-reading this issue I noticed I may have misunderstood the goal: When you say "on the left side" you mean changing the font of both, name and type, and not only the name of the property, right? For some reason I was still thinking on the previous issue, which was only related to the property names (i.e. adding a colon after them).

If that's the case, then there is not any problem with the font size. If they both use the same font family, they both will have the same size:

![image](https://user-images.githubusercontent.com/61671655/99538604-7f7e5980-29ad-11eb-8367-78468e8415fc.png)

Just as an additional note, for some reason the font size changes when I add "sans-serif" as a fallback font family to "monospace". It makes the size to keep the same as it was before changing the font family to monospace (i.e. like on the picture I included some lines above in this comment). If I just keep "monospace" as the applied font family (without any fallback), the size of the affected text will shrink as I showed on the screenshot of my previous comment.

**Comment by djmitche** [comment]
I don't know much about web fonts, so I'm not much help on the size-change question.  But yes, I like the use of monospace in the entire left column, rather than mixing the two.

**Comment by helfi92** [comment]
Having all of the left panel be monospace sounds good to me. Given that monospace is a generic font, I don't think we will need another fallback font like sans-serif.

**Comment by Joaquin-M2** [comment]
> Having all of the left panel be monospace sounds good to me. Given that monospace is a generic font, I don't think we will need another fallback font like sans-serif.

Alright, then I will just remove the sans-serif fallback even though it will shrink the size of the font a little bit.

I will create a PR soon. Please, have a look at it and if you think the size should be increased (1.1rem is the right value to get the sans-serif size), just let me know and I will update it.
