### ISSUE TITLE
Include colons after all properties on the left

### ISSUE THREAD

**Issue by djmitche** [taskcluster/material-ui-json-schema-viewer#116]
For example:

![image](https://user-images.githubusercontent.com/28673/93262316-032f8600-f772-11ea-9609-11f85d24d2fe.png)

`lastFire` has a colon, but the other three properties are lacking colons.

**Comment by kkyeboah** [comment]
_reserving for pocket curation tools outreachy applicants_

**Comment by Joaquin-M2** [comment]
Hello @djmitche ! Could I be assigned to this issue, please? I am an Outreachy applicant.

**Comment by djmitche** [comment]
Sounds good to me (@kkyeboah let me know if this isn't OK!)
