### ISSUE TITLE
Create renderArray() method

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#13]
create a method to render array type schemas

- take schema as input and parse to input into leftRow and rightRow
- make sure for the array items to be encapsulated between `[` and `]`
- each of the array items should call on `renderSchema`

**Comment by JiwoonKim** [comment]
Note about **indentations**:
- use `margin` or `padding` for indentations (instead of {` `})
- specifically use material-ui theme for spacing margins
- ex. `marginLeft: theme.spacing(1)`

**Comment by JiwoonKim** [comment]
Following discussion in https://github.com/taskcluster/material-ui-json-schema-viewer/pull/5#discussion_r354199498, I found that the `contains` keyword needs a bit speculation on how it will be displayed in the schema table. 

Per documentation, `contains` is defined as: 
> While the items schema must be valid for every item in the array, the contains schema only needs to validate against one or more items in the array.
https://json-schema.org/understanding-json-schema/reference/array.html#array

I think this could maybe be similar to the `required` keyword in object type schemas. So maybe we could display this same as an item in an array, but with `*` to emphasize that it is a required item in the array.

However, a **few ambiguities** exist in that
1. Is the `contains` keyword contradictory to `items` keyword (in other words, can only one of the two keywords be present at a time or can they both be present at the same time) ?
2. If both can exist at the same time, does the item specified in the `contains` keyword has to match the item specified in `items` or can it be a completely separate item?

**Comment by JiwoonKim** [comment]
Also, some additional **ambiguities** on the `additionalItems` keyword:

While it is easy to simply put the keyword in the right panel when the value is set like
`additionalItems: true` or `additionalItems: false`:

<img src="https://user-images.githubusercontent.com/29671309/70994319-4c827480-2111-11ea-9ada-3a82f12fead7.png" width="600px" />

in the case when additionalItems is set to a schema:
```js
{ 
   type: 'array',
   // additionalItems can only be used for tuple-validation
   items: [
      { type: 'number' },
      { type: 'string' },
   },
   // additionalItems is set to a schema
   additionalItems: { "type": "integer" },
}
```
simply displaying such in the right panel like in the former example will not work (especially when the schema defined for the additionalItems is more complex)

**Comment by helfi92** [comment]
> The documentation simply demonstrates the latter case, so would it be safe to assume that only the latter case applies and that the former case does not happen at all?

I believe both cases are correct.

> Also, would like to know your thoughts on the idea above of using contains like required properties in objects (using *)!

What do you think if we use the mathematical symbol of contains which is `⊃`.

> So I was thinking maybe in cases where additionalItems is defined as a schema, we could also display the defined schema like an array item at the end of the rows for items (and indicate on the right panel of that row that this is an additionalItem)!
What do you think of this idea?

Makes sense to me :)
