### ISSUE TITLE
Create renderObject() method

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#14]
create a method to render object type schemas

- take schema as input and parse to input into leftRow and rightRow
- make sure for the object properties to be encapsulated between `{` and `}`
- each of the object properties should call on `renderSchema`

  - if the object property has a `name`, preserve it and pass it down as input to `renderSchema`
  - change `renderSchema` to take input for name keywords for object properties

**Comment by JiwoonKim** [comment]
See https://github.com/taskcluster/material-ui-json-schema-viewer/issues/13#issuecomment-565368058 for indentation specifics

**Comment by JiwoonKim** [comment]
Seems like `dependencies` can get really complicated in JSON schemas!

At the moment, since dependencies are defined as objects, they are displayed like this:

```js
// CREDIT_CARD property has dependency on BILLING_ADDRESS property
{ 
  type: 'object',
  properties: {
      credit_card: { ... },
      billing_address: { ... },
  },
  dependencies: {
     credit_card: ["billing_address"],
  }
}
```

<img src="https://user-images.githubusercontent.com/29671309/71354811-6b28b580-25c0-11ea-90b4-2adff13a640d.png" width="300px" />


I was thinking of further developing the schema viewer by displaying the `dependency` for each concerning property instead like this:

| when defined simply (example above) | when defined as a complex subschema |
|:---|:---|
| <img src="https://user-images.githubusercontent.com/29671309/71355407-4c2b2300-25c2-11ea-8c99-1eee11ef9fff.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/29671309/71355621-f30fbf00-25c2-11ea-9656-1f5fd489df5c.png" width="300px" /> |

so that users can see more clearly on which property has a dependency.

However, there is one small problem regarding this new display. In cases where dependencies are specified for non-defined properties, the dependency would not be displayed. For example, 

```js

{ 
  type: 'object',
  properties: {
      billing_address: { ... },       // there is no CREDIT_CARD property
  },
  dependencies: {
     credit_card: ["billing_address"], // CREDIT_CARD depends on BILLING_ADDRESS
  }
}
```
In this case, a dependency would not be displayed at all. 

I understand that this is an extreme corner case, but was wondering if we should consider these cases as well.

@helfi92 What do you think about the idea of changing the `dependencies` to each property instead? And if we decided to change it this way, how should we deal with the edge cases defined as above (if theses cases actually exist at all)?

**Comment by helfi92** [comment]
> Seems like dependencies can get really complicated in JSON schemas!

Agreed. Dependencies are an advanced feature that I don't think many people use this. As far as I can see, we don't use it in Taskcluster.

> However, there is one small problem regarding this new display. In cases where dependencies are specified for non-defined properties, the dependency would not be displayed.

I'm thinking maybe we can just rely on the info icon for dependencies. There will also be less confusion with users about why dependencies are sometimes hidden and sometimes displayed.
