### ISSUE TITLE
Find more consistent way to display types

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#20]
**Describe the Bug**

<img src="https://user-images.githubusercontent.com/29671309/70909912-e4208e00-2051-11ea-9e45-66c89ddfb4c9.png" width="350px" />

Currently, `default` schema types are denoted by (ex. middle row in example above)
- "..." in the left panel
-  (type) specified explicitly in the right panel

while `array` and `object` schema types are planned to be denoted by (ex. first row in example above)
- brackets in the left panel
-  no (type) specified in the right panel

which seems **inconsistent** in properly delivering information.

Also, the use of `"..."` can be confusing even though the type will be specified in the relating right panel.

**Expected Behavior**
1. a consistent way of conveying types between default types and array, object types
2. replace the use of `"..."`

**Comment by JiwoonKim** [comment]
I was thinking maybe we could remove the `type` descriptions from the right panel completely (even for default types) so that the right panel can focus on additional keywords instead, and leave the left panel to denote more specifically on the types.

So on the left panel, arrays and object types will still use brackets to convey which types they are, while default types (strings, numbers, booleans, etc.) will use a markdown like syntax to replace the `"..."`.

An example of the changed outcome (using the example above) would be:
<img src="https://user-images.githubusercontent.com/29671309/70910802-cfdd9080-2053-11ea-8386-6ca19932ebe4.png" width="350px" />


@helfi92 What do you think of this idea?

**Comment by helfi92** [comment]
> @helfi92 What do you think of this idea?

I like this idea, a lot. I agree with you. Let's do it!
