### ISSUE TITLE
Create JSON schema test cases

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#3]
- create general schemas for testing purposes
- create edge cases (ex. empty array from [bugzilla #1591232](https://bugzilla.mozilla.org/show_bug.cgi?id=1591232) )

References:
- [json-schema documentation](https://json-schema.org/understanding-json-schema/)
- [`react-schema-viewer` schema examples](https://github.com/taskcluster/react-schema-viewer/tree/master/schemas)

**Comment by JiwoonKim** [comment]
@helfi92 
I hope it's okay that I've created an issue for the next task.

I was thinking of making a `/schemas` folder like in react-schema-viewer project
and within it holding the following folders and files:

`/schemas`
- `/basic-data-types`

   - `/default-types`
      - string.json (
      - numeric.json
      - boolean.json
      - null.json

   - `/array-types`: 
      - array-list.json
      - array-tuple.json
      - empty-array.json (no items)

   - `/object-types`
      - object.json

- `/ref-types`
   - reference-def.json
   - circular-reference.json

- `/combination-types`
   - all-of.json
   - one-of.json
   - any-of.json
   - not.json

- `/demo`
   - list-clients-response.json (Taskcluster example)
   - a complex circular-referencing schema example

**Comment by helfi92** [comment]
> I was thinking of making a /schemas folder like in react-schema-viewer project
and within it holding the following folders and files:

Sounds like a good plan! I like it.

>  I hope it's okay that I've created an issue for the next task.

Thank you for creating the issue :) It would probably be a good idea to have this issue associated with the project view that I created. You can do that by clicking on "Projects" then on "Outreachy Round 19" .

![Screen Shot 2019-12-03 at 10 08 56 AM](https://user-images.githubusercontent.com/3766511/70062945-07106400-15b5-11ea-9a78-2d19f8e121e2.png)
