### ISSUE TITLE
Escape complex schema definitions

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#30]
@djmitche proposed a great idea on using a **common visual indicator** to deal with more obscure/complex parts of the schema! (ex. displaying `additionalItems`: see https://github.com/taskcluster/material-ui-json-schema-viewer/issues/13#issuecomment-566517611 )

Specifically, the idea is to: 
> have some common visual indicator that the schema defines something that can't be represented, and a way for users to switch to a view of the schema source. 
```js
   additionalItems: ⚠️ 
   // The alert icon has a tooltip: 
   // "Additional items must match a sub-schema.  See the JSON-schema source for details."
```
> This might be a nice way to not worry about these complex cases right now, but still provide full information to users.  It would also make it easy to search the source later to find complex cases that have not yet been addressed.

-------------------------------

I think this is a great idea! 💯 👍 (thanks @djmitche !)

Will be implementing the following:
1. keywords defined with objects (`additionalitems`, `additionalProperties`, etc.) will display `additionalItems: ⚠️`  format, where the alert icon has a tooltip.

2. switch `modes` feature in schema viewer
    - `table` mode: displays two-layer table
    - `source` mode: displays the schema source

@helfi92 
I think we can implement the first part after/or while developing `renderObjects`,
while the second part can be something we can add at the end of developing the schematable.

**Comment by helfi92** [comment]
> I think we can implement the first part after/or while developing renderObjects,
while the second part can be something we can add at the end of developing the schematable.

Makes sense to me.
