### ISSUE TITLE
Create Table with Scrollable Panels

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#4]
**Describe component:**
1. `< SchemaTable />` should be a **two-column layout table**
   - **Left Column**: JSON Data Structure
   - **Right Column**: Information (which consists of two parts)
      - meta data: data type, and other fields
      - description

2. Each column of the table should be **scrollable**

**Expected Mockup UI**
![image](https://user-images.githubusercontent.com/29671309/70056630-22b05480-161f-11ea-8ba8-0719f8d2fdc1.png)

**Comment by JiwoonKim** [comment]
@helfi92 
A few questions on how the component layout should be implemented:

1. **Two-column Layout**: since the information column (the white columns on the right side in the mockup UI above) is actually constituted of two parts (meta-data part & description part) 
   - should the table actually have 3-columns but just visually be displayed as if it has two-columns? (ex. have the 1st column in one color while 2nd and 3rd columns are both in another color OR have a column border between the 1st and 2nd columns but not having one between the 2nd and 3rd columns) this is how I originally created the layout in the [prototype](https://codesandbox.io/s/material-ui-json-schema-viewer-oq3dd)

   - or should the table just have 2-columns? (in this case, how should the information column be divided into two parts?)

2. **Scrollable columns**:

    -

**Comment by helfi92** [comment]
Great question. Given that we are not using column header names, then it's probably ok not to use a table and just rely on using a bunch of divs. The thing that makes it seem like a table is the horizontal lines but that's just here to help users have a better experience scanning the viewer. That should help in making the panels scrollable. Do you agree?

**Comment by JiwoonKim** [comment]
> Great question. Given that we are not using column header names, then it's probably ok not to use a table and just rely on using a bunch of divs. The thing that makes it seem like a table is the horizontal lines but that's just here to help users have a better experience scanning the viewer. That should help in making the panels scrollable. Do you agree?

That would definitely make it easier to create! 🚀

**Comment by JiwoonKim** [comment]
A few notes on how the `< SchemaTable />` component should look like:

- consists of `Panels` instead of columns since no longer using table tags
   - left panel: holds JSON data structure
   - right panel: holds information about data
- each panel:
  - uses a wrapper div to make it scrollable
  - contains an `array` of html tags in order to align the rows between panels by indexes
  - the data within the panels should not be too dense and optimize space
- the `theme color` of the entire schema table component should be customizable

**Comment by JiwoonKim** [comment]
Looked into some alternative methods and found `subgrid`
https://www.w3.org/TR/css-grid-2/#subgrids

Unfortunately, only Firefox seems to support this at the moment
since CSS Grid Layout Module Level 2 is still a working draft.

Maybe if `subgrid` passes as standards and is supported by more browsers in the near future,
this can be something the schema-viewer can be built-on with some refactoring! 🌈 

In the meantime, I think the most suitable solution would be to use the < br /> tags
to fill in the rows in the left panel so that they align with related rows in the right panel.
(we would only need to count how many keywords will be displayed in the relating row's right panel)

**Comment by helfi92** [comment]
> In the meantime, I think the most suitable solution would be to use the < br /> tags
to fill in the rows in the left panel so that they align with related rows in the right panel.
(we would only need to count how many keywords will be displayed in the relating row's right panel)

I trust your research :) I'll need to learn CSS grids (it's on my TODO) to be able to contribute to this discussion. I've previously only used flexbox hehe.
