### ISSUE TITLE
Refactor skipKeywords constants from row components

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#44]
**Describe the Bug**
Although `skipKeywords` in NormalLeftRow and NormalRightRow should have the exact same values, they are defined separately in each of the component, which makes it inefficient when changing the values within `skipKeywords` is necessary.

(FYI, `skipKeywords` is currenlty used for the following purposes) :
- used to skip displaying certain keywords in NormalRightRow
- used to create blank line paddings to match number of lines within a row in NormalLeftRow
```js
const skipKeywords = [
    'type',
    'name',
    'description',
    'items',
    'contains',
    'properties',
];
```
**Expected Behavior**
It would be great if we can manage the values listed in `skipKeyword` in a single place. 

Although defining them in the parent component SchemaTable could be a solution, I feel that this is a bit cluttery in that we have to pass down `skipKeyword` as props even though it's a constant value.

Also, since we already have `schema`, `classes`, `indent` as props in each of the Row components, I think it would be great to instead create a `constants.js` file within the `/component` folder and define skipKeywords there and then simply import the values in places necessary :)

**Comment by JiwoonKim** [comment]
@helfi92 what do you think about this idea?

**Comment by helfi92** [comment]
That's a great idea! Rather than put it inside `src/components/constants.js`, we could put it inside `src/utils/constant.js`.
