### ISSUE TITLE
Create RefSchemaRow component

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#46]
create a component that can expand and collapse

- take a `$ref` type schema as input
- a single RefRow should constitute of an expandable `leftRow` and `rightRow`
- add a button to expand and shrink the ref row 

  - make sure both the leftRow and rightRow's expand/shrink state match
- when expanded, the `$ref` should be dynamically fetched and call on renderSchema

**Comment by JiwoonKim** [comment]
A few  important blockers and solutions needed to be discussed for implementing this component:

**Blockers**
1. While the expand/shrink feature needs to dynamically add or remove rows within the schemaTable, the current schemaTable utilizes array structures to store rows for each panels (leftRows and rightRows) which is inefficient in inserting and deleting rows in the middle. It would be great to find a way to implement expand/shrink feature without having to change the array structure of leftRows and rightRows.

2. How and where to store the state of expand/shrink of a single refRow? (particularly a tricky issue for circular references)

**Solutions**

**Comment by JiwoonKim** [comment]
A better solution suggested in a meeting this week:

1. create a `tree structure` to represent schema structure (store in state)
```js
const node = {
  schema: { ... }
  children: [ ... ],
  isExpanded: true/false,
}
```
2. render the schemaTable based on the structure of the tree

**Comment by JiwoonKim** [comment]
> This way, not only is it more efficient to dynamically store new nodes (for refs when expanded), it's also easy to maintain the state of ref schema's state of when expanded or shrunk 🔥 .

Looked in more detail to evaluate how we could implement this solution and I think this is a great solution 💯 ! The details in how we would implement this are the following:

1. __create a `tree` to have a rough sketch of the schemaTable structure__
   - store the `root node` as a const 
   - create nodes one-by-one by reading the schemas and sub-schemas
   - link array items/contains, object properties, combination options as `children` nodes
   - $ref Types are stored as `refNode` while the rest are simply stored as `node`
   - create a state `isTreeChanged` to track any changes made to the tree structure (necessary to trigger a re-render of the tree illustrated in step 2 for when any $ref is expanded/shrunk)
   

2.  __traverse the tree to create rows in schemaTable__
    - use `leftRows` and `rightRows` to store rows created (arrays)
    - traverse all the nodes in the tree starting from the root node (use DFS to ensure subschemas are contained within schemas)
    - at each node, call on `createNormalRow()` to create a leftRow and rightRow each and store them into leftRows and rightRows

3. __render the `leftRows` and `rightRows` into each of the panels__

4. __if $ref row expand

**Comment by JiwoonKim** [comment]
➕ __Evaluation of Efficiency__ 
[expanding on array structure](https://github.com/taskcluster/material-ui-json-schema-viewer/issues/46#issuecomment-572436806) vs. [adding intermediary tree structure](https://github.com/taskcluster/material-ui-json-schema-viewer/issues/46#issuecomment-572896130)

- n = size of schema (number of elements within a schema or sub-schemas)
- m = size of $ref definition's schema (number of elements within the $ref definition)

| | Render Initial SchemaTable | $ref expand/shrink (add/remove rows) |
|:---|:---|:---|
| Arrays within Array | O(n) - read each schema/subschema and create each row | O(m) - add or remove extra m lines for refRow | 
| Array + Tree | O(n) - create tree structure and then, traverse each node in tree to create each row | O(n + m)  - create extra m lines for refRow and re-render tree structure  |

- Although it is a bit more costly when adding a tree structure in terms of time and space complexity, the tree structure does make it more logical and semantic in terms of the structure since it is able to avoid rows containing rows. 
- Also, because $ref is not as commonly used and additional costs are only added when expanded or shrunk, the costs can be considered as amortized as well.

**Comment by helfi92** [comment]
Thank you for being elaborate. This will help a lot during the review as well.

> when isTreeChanged is set to true, trigger re-render in schemaTable component (go to step 2)

We could probably rely on having the tree be used as a prop and let react take care of the re-render whenever the tree changes (whenever the state is updated).

**Comment by JiwoonKim** [comment]
> We could probably rely on having the tree be used as a prop and let react take care of the re-render whenever the tree changes (whenever the state is updated).

Great idea! 👍 
Will implement a higher-level `SchemaViewer` component which is where the schema tree will be created and returns a `SchemaTable` component (which takes the tree as a prop). The `SchemaViewer` component will also be able to include the mode feature specified at #37 :)

**Comment by JiwoonKim** [comment]
> We could probably rely on having the tree be used as a prop and let react take care of the re-render whenever the tree changes (whenever the state is updated).

Seems like updating the `SchemaTree` state is a bit of a complex issue since the two necessary tasks for expanding or shrinking a refNode have some major contradictions: 
- need to mutate the values of a particular `refNode` within a tree, which is a nested object
- must leave the original tree state as-is and only update the state in an immutable way: `setTreeState(new Tree)`

So basically, we __need to mutate part of the tree while also maintaining the original state of the tree__.

A couple of __solutions__ to this would be:
1. __create a deep copy of the tree and mutate the copied one's refNode__
   - need to traverse the original tree to find the path (ex. `children[3].children[1].children[0]...`) to the corresponding refNode
   - then traverse the same pathway through the copied tree to find the corresponding copy of the refNode and mutate its values
    - update the tree state using the copied tree

2. __use external libraries__, such as [immer.js](https://immerjs.github.io/immer/docs/example-setstate)
   - similar to the first solution, need to traverse the original tree to find the position of the refNode
   - use the position to access and update the state while maintaining immutability
```js
setTreeState(produce(draft => {
    draft.children[3].children[1].children[0] = // change values here
})
```

3. __create a copy of the tree and use the copy as prop for schemaTable__
   - no need to traverse the tree to find the refNode since it's values can be directly mutated
   - a bit nonsensical since we don't actually use the original tree state, only its copy (the original tree is more like insurance)

@helfi92 
I personally think solution 3 makes the code cleaner and simpler, while solution 1 or 2 are a bit more complex. What do you think about the solutions?
