### ISSUE TITLE
Add other cases for dynamically fetching $ref schemas

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#56]
On expand, $ref type schemas should dynamically fetch the schemas. The following are the common ways a $ref's source may be defined as:

1. References a __sub-schema__ within the current schema ( ex. `schemas/refType/simpleReference.json` ) -> ( resolved in #54 ✔️  )
```json
$ref: '#definitions/name'
```

2. References a __URI__ (ex. `schemas/demo/metadata-metaschema.json`)
```json
$ref: 'http://json-schema.org/draft-06/schema#'
```

3. References a __file using the current path__ (ex. `schemas/demo/worker-list.json`)
```json
$ref: 'worker-full.json#'
```

**Comment by JiwoonKim** [comment]
Solutions to 2️⃣  and 3️⃣ : 
- 2️⃣ : fetch by URL (absolute paths) 
- 3️⃣ : fetch by creating a URL using the relative path
  - use `new URL(relative_path, base_url)` to construct an absolute path (URL)
  - see example reference in Taskcluster below
```js
// example used in Taskcluster's schemaTable component
const fullSchemaPath = new URL(schemaPath, window.location.href);

// For our case, we can do the following instead:
const sourceUrl = new URL(schema.id, window.location.href);
```

**Reference**: 
https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/SchemaTable/index.jsx#L150

**Comment by djmitche** [comment]
The approach that Ajv itself takes is that the schemas must all be given in advance and are stored according to their $id. So, it does not actually fetch anything itself.  We use this [here](https://github.com/taskcluster/taskcluster/blob/master/libraries/validate/src/index.js#L113-L116).  This allows the caller to be sure that only the given schemas are displayed, and avoids issues of CORS, malicious content injection, data leakage, and so on.

**Comment by JiwoonKim** [comment]
> The approach that Ajv itself takes is that the schemas must all be given in advance and are stored according to their $id. So, it does not actually fetch anything itself. We use this [here](https://github.com/taskcluster/taskcluster/blob/master/libraries/validate/src/index.js#L113-L116). This allows the caller to be sure that only the given schemas are displayed, and avoids issues of CORS, malicious content injection, data leakage, and so on.

This is great! We can have the schema viewer give all the schemas as input so that it can create an Ajv instance to store all the schemas as a database. So that when a $ref is expanded, it can refer to the database instead of actually fetching it :)

**Comment by JiwoonKim** [comment]
For $refs defined as URLs,
> 2. References a URI (ex. schemas/demo/metadata-metaschema.json)
$ref: 'http://json-schema.org/draft-06/schema#'

we can add them into the references database (object of Ajv mentioned in the previous comment) similarily as how schemaTable uses it in Taskcluster https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/SchemaTable/index.jsx#L120-L124
