### ISSUE TITLE
Alpha Release

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#57]
release alpha version

1. publish the project as `npm` package (closed in #89 )
2. create `Taskcluster` PR to test the integration of project (closed in https://github.com/taskcluster/taskcluster/pull/2412)

**Comment by JiwoonKim** [comment]
Regarding the second part (create Taskcluster PR to test integration): 
- replace the react-schema-viewer's schemaTable with material-ui-json-schema-viewer's `SchemaViewer` component
- remove $RefParser's dereferencing since we need to preserve all `$ref`s (they should not be replaced by referencing)

**Comment by helfi92** [comment]
Alpha release was a success!

**Comment by JiwoonKim** [comment]
Successfully released alpha version!
