### ISSUE TITLE
Add Loading animation to expand/shrink

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#58]
Add loading animation effect to expand/shrink $ref feature

**Comment by JiwoonKim** [comment]
Maybe use `@mozilla-frontend-infra/components/Spinner` 
(https://github.com/mozilla-frontend-infra/components) 

See example of how it is used in Taskcluster: https://github.com/taskcluster/taskcluster/blob/master/ui/src/components/SchemaTable/index.jsx

**Comment by helfi92** [comment]
This is probably no longer needed if we're not going to fetch a schema anymore :)

**Comment by JiwoonKim** [comment]
Closing issue since no longer needed.
