### ISSUE TITLE
Add feature to support multiple type specification

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#68]
**Describe the Bug**
current schema viewer does not support multiple types

JSON schema doc specifies possibility of multiple types (https://json-schema.org/understanding-json-schema/reference/type.html#type)
> The type keyword may either be a string or an array:
If it’s a string, it is the name of one of the basic types above.
If it is an array, it must be an array of strings, where each string is the name of one of the basic types, and each element is unique. In this case, the JSON snippet is valid if it matches any of the given types.
...
For each of these types, there are keywords that only apply to those types. For example, numeric types have a way of specifying a numeric range, that would not be applicable to other types. In this reference, these validation keywords are described along with each of their corresponding types in the following chapters.

⚠️ One concern is that validation keywords only apply to its corresponding types. This means that in order to display multiple types we would need to categorize validation keywords into which of the specified types is belongs to and associate those keywords with that type. For example:
```js
{ 
  type: ["number", "string"],
  minimum: 0,  // only applies to number type
  maxLength: 10,  // only applies to string type
}
```

**Comment by JiwoonKim** [comment]
Three possible solutions:

1. __simply display multiple types without any validation keyword matching__
   - just display `type: 'string', number' ...`
   - display all the validation keywords without any matching of types
```
   'number', 'string'  | minimum: 0
                       | maxLength: 10
```

2. __render multiple types as a `oneOf` combination type__
   - makes use of the combination type rendering (`oneOf` means the schema can be one of the subschemas specified)
   - would need to match the validation keywords with the specified types and use each of those types as subschemas
   - displays schemas where its type and validation keywords match
```
// One of            |
   'number'          | minimum: 0
   ' string'         | maxLength: 10
```

3. __use ℹ️ icon for complex schemas__
   - this avoids complications and makes sure that the viewer doesn't show the wrong schema
   - does not provide useful information (simply directs the user to refer to the source instead)
```
ℹ️           | keyword ? or ℹ️  as well?
```

**Comment by helfi92** [comment]
Option 1 or 3 sounds good to me. I think I am leaning more towards the first option but I'll let you decide what you think makes most sense. Option 2 is the idea case but will probably involve adding complexity which I'd rather avoid for now, at least for the first iteration of this component.
