### ISSUE TITLE
UX enhancements

### ISSUE THREAD

**Issue by helfi92** [taskcluster/material-ui-json-schema-viewer#76]
1. Hover effect on the icon is too big relative to the icon. Let's fix that.
<img width="178" alt="Screen Shot 2020-02-13 at 5 39 58 PM" src="https://user-images.githubusercontent.com/3766511/74485191-32061680-4e88-11ea-901b-14dd5dce8713.png">

2. Chip is too close to the cell boundary. Let's give it some breathing space :)

<img width="214" alt="Screen Shot 2020-02-13 at 5 39 46 PM" src="https://user-images.githubusercontent.com/3766511/74485192-329ead00-4e88-11ea-892a-0139fbae3d0b.png">

3. Should be able to display markdown.

3a) 

<img width="1540" alt="Screen Shot 2020-02-13 at 5 40 50 PM" src="https://user-images.githubusercontent.com/3766511/74485185-316d8000-4e88-11ea-8433-78c7c92651f3.png">

3b)

<img width="809" alt="Screen Shot 2020-02-13 at 5 40 25 PM" src="https://user-images.githubusercontent.com/3766511/74485190-32061680-4e88-11ea-9a81-dde10e4c1af7.png">

**Comment by helfi92** [comment]
Other enhancements:

4) Experiment with a thinner border for the separation of the left and right panel. Maybe we can make it have a width similar to the bottom border of a cell. Happy to discuss if you disagree with this.
5) Add some breathing space between the border and the text of the right panel
![Screen Shot 2020-02-19 at 4 55 04 PM](https://user-images.githubusercontent.com/3766511/74880135-974e8180-5338-11ea-9df4-df5a4a07a92a.png)
6) Extend the horizontal line to the end when opening refs
![Screen Shot 2020-02-19 at 4 49 22 PM](https://user-images.githubusercontent.com/3766511/74880237-c664f300-5338-11ea-9c57-edaedcc280f7.png)

**Comment by JiwoonKim** [comment]
Fixed issues 1-5. Issue 6 will be fixed in separate issue #97.
