### ISSUE TITLE
Deploy Storybook as gh-pages

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#90]
- deploy storybook as gh-pages
- add description to repo and line to launched gh-pages

**Comment by helfi92** [comment]
In the README, a section saying how to deploy the storybook after npm publishing it would be helpful.

**Comment by JiwoonKim** [comment]
Once #85 is successfully merged, will be able to deploy storybook. (because the pr modifies the example in Storybook) Instructions for storybook deployment have also been added in that pr in the meantime for #85 to be approved.

**Comment by helfi92** [comment]
This is done. Link is the repo description.
