### ISSUE TITLE
Fix $id prop error in Schema types

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#94]
**Describe the Bug**
`Schema` type in utils/prop-types.js require `$id` as a required field. However, child tree node's use the custom keyword `_id` instead within its schemas, which is why the following error occurs.

![image](https://user-images.githubusercontent.com/29671309/75340542-02b6c700-58d6-11ea-8de9-c2671766f9df.png)

**Expected Behavior**
enable `Schema` type to include either `$id` or `_id` as required field (must include at least one)

**Comment by helfi92** [comment]
What's the status of that?
