### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by helfi92** [taskcluster/material-ui-json-schema-viewer#95]
Perhaps publishing the first stable version tomorrow would make sense. Feel free to do it whenever you are ready. No need to worry for PRs that are still not approved. Once they get merged, we can publish 1.0.1, etc...

Don't forget to merge the approved open PRs before cutting the first stable release :)

**Comment by JiwoonKim** [comment]
Successfully published the first stable version: `1.0.0` :rocket:
