### ISSUE TITLE
Extend the horizontal border of rows

### ISSUE THREAD

**Issue by JiwoonKim** [taskcluster/material-ui-json-schema-viewer#97]
Extend the horizontal line to the end when opening refs

![image](https://user-images.githubusercontent.com/29671309/75416657-3e06d380-5972-11ea-9932-bc24977f9485.png)

**Comment by JiwoonKim** [comment]
This might be a complicated issue since we need to be able to apply the border property to overflowing elements when initially the size it confined to the entire table's width.

![image](https://user-images.githubusercontent.com/29671309/75423222-9f826e80-5981-11ea-9fac-2fe9c1c57925.png)

Maybe a possible solution would be to :
- create the left panel in full-width so that it can apply border lines to all of its children (=rows)
- render the right panel on top of the left panel using the z-index
- add a scroll to the left panel so that it is always scrollable and users can see the hidden parts beneath the right panel

Should we try this solution? What do you think @helfi92 ?

**Comment by djmitche** [comment]
Now that #114 has landed, I think this is no longer an issue (but we've introduced other issues..)
